apiVersion: v1
kind: Service
metadata:
  name: kenellorando
  labels:
    app: kenellorando.com
spec:
  type: NodePort
  ports:
  - nodePort: 30001
    port: 80
    protocol: TCP
  selector:
    app: kenellorando.com
