apiVersion: v1
kind: Service
metadata:
  name: stc
  namespace: stc
  labels:
    run: stc
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
  selector:
    run: stc
