apiVersion: v1
kind: Service
metadata:
  name: kenellorando
  labels:
    app: kenellorando.com
spec:
  type: LoadBalancer
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: kenellorando.com
